export const CONFIG = {
  startDate: new Date("2023-06-15T00:00:00"),
  colors: {
    pink: "#ff6b8a",
    pinkSoft: "#ffb3c6",
    rose: "#ff8fa3",
    pinkDeep: "#e8457c",
    gold: "#e8b86d",
    peach: "#ffcdb2",
    cream: "#fff8f0",
  },
  constellation: [
    { label: "Your laugh", x: 30, y: 20 },
    { label: "Your kindness", x: 55, y: 15 },
    { label: "How you scrunch your nose", x: 70, y: 30 },
    { label: "Your terrible jokes", x: 60, y: 50 },
    { label: "The way you see the world", x: 75, y: 65 },
    { label: "Your hugs", x: 50, y: 75 },
    { label: "How brave you are", x: 30, y: 65 },
    { label: "Your smile - God, your smile", x: 25, y: 45 },
  ],
  memories: [
    { text: "Our first date", rotate: -4 },
    { text: "That road trip playlist", rotate: 3 },
    { text: "2am conversations", rotate: -2 },
    { text: "Dancing in the kitchen", rotate: 5 },
    { text: "Your head on my shoulder", rotate: -3 },
    { text: "That time we got lost", rotate: 2 },
  ],
  promises: [
    "I promise to always make you laugh - even when you're mad at me.",
    "I promise to hold your hand through the hard days.",
    "I promise to never stop trying to be better for you.",
    "I promise to always save you the last bite.",
    "I promise to love you louder on the days you feel quiet.",
    "I promise to choose you - again and again and again.",
  ],
  loveLetter: [
    { text: "My Dearest Love,", pause: 1200, style: "heading" },
    { text: "", pause: 600 },
    { text: "I've rewritten this a hundred times", pause: 200 },
    { text: "trying to find the perfect words.", pause: 400 },
    { text: "But the truth is - there are no perfect words", pause: 200 },
    { text: "for what you mean to me.", pause: 800 },
    { text: "", pause: 600 },
    { text: "You walked into my life", pause: 200 },
    { text: "and rearranged everything I thought I knew", pause: 200 },
    { text: "about what it means to love someone.", pause: 800 },
    { text: "", pause: 600 },
    { text: "You make the ordinary feel sacred.", pause: 400 },
    { text: "A Tuesday with you is better than", pause: 200 },
    { text: "any adventure without you.", pause: 800 },
    { text: "", pause: 600 },
    { text: "I don't need grand gestures.", pause: 300 },
    { text: "I just need you -", pause: 400 },
    { text: "your morning voice,", pause: 300 },
    { text: "your sleepy eyes,", pause: 300 },
    { text: "your hand reaching for mine", pause: 200 },
    { text: "without even thinking about it.", pause: 800 },
    { text: "", pause: 600 },
    { text: "You are my favorite person.", pause: 300 },
    { text: "My best friend.", pause: 300 },
    { text: "My home.", pause: 1000 },
    { text: "", pause: 600 },
    { text: "I love you.", pause: 500 },
    { text: "Not just today - but in the forever kind of way.", pause: 1000 },
    { text: "", pause: 600 },
    { text: "Happy Valentine's Day, my love.", pause: 0, style: "heading" },
  ],
  finaleWords: ["I love you", "Forever", "My heart", "Always", "Yours", "Infinity", "Always yours", "Home", "Soulmate", "Beloved"],
};
